flake: fix usage of overlay in other flakes
Without this, it was possible to importer the jupyterWith attribute
without its python and haskell overlays, thus ending up with errors like

error: attribute 'jupyter_contrib_core' missing